##################################
# Deployment
##################################
className: io.streamnative.data.feeds.realtime.coinbase.WebSocketSource
tenant: feeds
namespace: realtime
name: coinbase-live-feed
topicName: persistent://feeds/realtime/coinbase-livefeed
configs:
  websocketURI: "wss://ws-feed.exchange.coinbase.com"
  subscription: "{ \"type\": \"subscribe\", 
    \"channels\": [\"ticker\", \"rfq_matches\", \"auctionfeed\"], 
    \"product_ids\": [ \"ETH-USD\", \"BTC-USD\", \"USDT-USD\", \"SOL-USD\", \"XRP-USD\"
    \ , \"DOGE-USD\", \"ADA-USD\", \"LTC-USD\" ] }"

##################################
# Processing
##################################
processingGuarantees: AT_MOST_ONCE
schemaType: STRING
logTopic: persistent://feeds/realtime/coinbase-live-feed-log