---
apiVersion: compute.functionmesh.io/v1alpha1
kind: Source
metadata:
  name: coinbase-live-feed
  namespace: coinbase-demo
spec:
  image: localhost:32000/coinbase-live-feed:latest
  className: io.streamnative.data.feeds.realtime.coinbase.WebSocketSource
  tenant: public
  namespace: default
  clusterName: test-pulsar
  replicas: 1
  maxReplicas: 2
  sourceConfig:
    websocketURI : "wss://ws-feed.exchange.coinbase.com"
    subscription: "{ \"type\": \"subscribe\", 
    \"channels\": [\"ticker\", \"rfq_matches\", \"auctionfeed\"], 
    \"product_ids\": [ \"ETH-USD\", \"BTC-USD\", \"USDT-USD\", \"SOL-USD\", \"XRP-USD\"
    \ , \"DOGE-USD\", \"ADA-USD\", \"LTC-USD\" ] }"
    maxReconnectAttempts: "10"
    reconnectBaseDelayMs: "1000"
  output:
    topic: persistent://feeds/realtime/coinbase-livefeed
    typeClassName: java.lang.String
  resources:
    requests:
      cpu: "0.5"
      memory: 1G
    limits:
      cpu: "1"
      memory: 2G
  pulsar:
    pulsarConfig: "pulsar"
  java:
    jar: "/pulsar/lib/coinbase-live-feed-1.0.1.jar"
    # use "" to read jar from local file system
    jarLocation: ""

---
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: coinbase-feed-router
  namespace: coinbase-demo
spec:
  className: io.streamnative.data.feeds.realtime.coinbase.WebsocketFeedRouter
  replicas: 1
  maxReplicas: 2
  image: localhost:32000/coinbase-websocket-feed-router:latest
  logTopic: persistent://feeds/realtime/coinbase-feed-router-log
  input:
    topics:
      - persistent://feeds/realtime/coinbase-livefeed
    typeClassName: java.lang.String
  funcConfig:
    TopicMap:
      rfq_match: persistent://feeds/realtime/coinbase-rfq
      ticker: persistent://feeds/realtime/coinbase-ticker
      auction: persistent://feeds/realtime/coinbase-auction
  resources:
    requests:
      cpu: "0.5"
      memory: 1G
    limits:
      cpu: "1"
      memory: 2G
  pulsar:
    pulsarConfig: "pulsar"
  java:
    jar: "/pulsar/lib/coinbase-websocket-feed-router-1.0.1.jar"


---
# Legacy ConfigMap - replaced by pulsar-config ConfigMap
# This is kept for backward compatibility with existing Pulsar Function deployments
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsar
  namespace: coinbase-demo
data:
  webServiceURL: http://192.168.0.200:8080
  brokerServiceURL: pulsar://192.168.0.200:6650