---
apiVersion: v1
kind: Deployment
metadata:
  labels: {}
  name: test5
  namespace: default
runningJobInfo:
  runningSubtaskCount: 2
  totalSubtaskCount: 2
spec:
  deploymentTargetId: null
  deploymentTargetName: vvp-jobs
  maxJobCreationAttempts: 4
  maxSavepointCreationAttempts: 4
  restoreStrategy:
    allowNonRestoredState: false
    kind: LATEST_STATE
  sessionClusterName: null
  state: RUNNING
  template:
    metadata:
      annotations:
        flink.queryable-state.enabled: 'false'
        flink.security.ssl.enabled: 'false'
    spec:
      artifact:
        entryClass: io.streamnative.coinbase.flink.stats.FlinkCoinbaseMovingAverage
        flinkImageRegistry: registry.ververica.com/v2.15
        flinkImageRepository: flink
        flinkImageTag: 1.20.1-stream1-scala_2.12-java17
        flinkVersion: '1.20'
        jarUri: s3://vvp/artifacts/namespaces/default/trades-moving-average-0.0.1.jar
        kind: JAR
      flinkConfiguration:
        execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
        execution.checkpointing.min-pause: 10s
        high-availability: kubernetes
        high-availability.type: kubernetes
        metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
        state.backend: filesystem
        taskmanager.memory.managed.fraction: '0.0'
        taskmanager.numberOfTaskSlots: '1'
        web.cancel.enable: 'false'
      environmentVariables:
        - name: PULSAR_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: pulsar-config
              key: pulsar.service.url
        - name: PULSAR_ADMIN_URL
          valueFrom:
            configMapKeyRef:
              name: pulsar-config
              key: pulsar.admin.url
        - name: PULSAR_AUTH_PLUGIN
          valueFrom:
            configMapKeyRef:
              name: pulsar-config
              key: pulsar.auth.plugin
        - name: PULSAR_AUTH_PARAMS
          valueFrom:
            secretKeyRef:
              name: pulsar-auth-secret
              key: auth-params
              optional: true
      logging:
        log4jLoggers:
          '': INFO
        loggingProfile: default
      parallelism: 1
      resources:
        jobmanager:
          cpu: 1
          memory: 2G
        taskmanager:
          cpu: 2
          memory: 2G
  upgradeStrategy:
    kind: STATEFUL